### ISSUE TITLE
Instructions on how to use the application required.

### ISSUE THREAD

**Issue by RishiRajGujadhur** [Dryzler/corona-bluetooth-app#1]
Hi Dryzler,

This is a great project. Have setup a server/db and configured the project then tested the app against 2 smartphones but its unclear on how to use the app. Can we update the read me document according to the following points:

1. Clarifying the encounter distance.
2. Whether the encounter distance can be changed/implemented.
3. What does "number of saved connection" means.
4. How and why is a connection registered.
5. Whose data does the "Clear database" button deletes.
6. How can this app be ran without an internet connection to encourage social distancing up to 1 meter or more.

Thank you for starting this project. Your work is much appreciated. 

Kind regards,
Rishi

**Comment by Dryzler** [comment]
Hi,

i have updated the readme with the the entry: Project status.

1. The encounter distance with the standard Bluetooth device detection is far too inaccurate, it's about 10 meters and goes through walls. I will have a look on Google and Apple and the pepp-pt project, and maybe adapt new possibilities to this solution.
